spring:
  config:
    activate:
      on-profile: dev
    import: optional:application-secret.properties

  datasource:
    driver-class-name: ${DB_NAME_DEV}
    url: ${DB_URL_DEV}
    username: ${DB_USER_DEV}
    password: ${DB_PW_DEV}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${DDL_OPTION_DEV}
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 500
    open-in-view: false