spring:
  profiles:
    active: local

  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 5MB

springdoc:
  packages-to-scan: com.pravo.pravo
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui.html
    url: /api-docs/json
    tags-sorter: alpha
    disable-swagger-default-url: true
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    enabled: true
  show-login-endpoint: true