name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-ci:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/gradle/wrapper
          key: "${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}"
          restore-keys: |
            ${{ runner.os }}-gradle-


      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: application-secret.properties 생성
        run: |
          cd src/main/resources
          echo "${{ secrets.PROPERTIES }}" > ./application-secret.properties

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build -x test
        shell: bash

      ### CD flow 시작 ###
      - name: Docker build 가능하도록 환경 설정
        uses: docker/setup-buildx-action@v2.9.1

      - name: Docker Hub에 로그인
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}

      - name: Docker image 빌드 및 푸시
        run: |
          docker build --platform linux/amd64 \
            -t pravo0904/pravo-server . 
          docker push pravo0904/pravo-server

  deploy-cd:
    needs: deploy-ci
    runs-on: ubuntu-22.04

    steps:
      - name: 도커 컨테이너 실행
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RELEASE_SERVER_IP }}
          username: ${{ secrets.RELEASE_SERVER_USER }}
          key: ${{ secrets.RELEASE_SERVER_KEY }}
          script: |
            cd ~
            ./deploy.sh
            docker image prune -f