name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: application-secret.properties 생성
        run: |
          cd src/main/resources
          echo "${{ secrets.PROPERTIES }}" > ./application-secret.properties

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build -x test
        shell: bash